@startuml
entity Artist{

}

entity Album{

}

entity Song{

}

entity Category{

}

entity Artist{

}

entity Playlist{

}

entity Podcast{

}

entity Episode{

}

entity User{

}

entity Concert{

}

@enduml